spring:
  application:
     name: users-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: users

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port